name: Autopost

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
    - cron: "5 */3 * * *"
    - cron: "10 */3 * * *"
    - cron: "15 */3 * * *"
    - cron: "20 */3 * * *"
    - cron: "25 */3 * * *"
    - cron: "30 */3 * * *"
    - cron: "35 */3 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  autopost:
    name: Autopost • ${{ matrix.category }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - category: News
            slug: news
            feeds_file: autopost/feeds_news.txt
            script: autopost/pull_news.py
            max_per_cat: "10"
            schedule: "0 */3 * * *"
          - category: Crypto
            slug: crypto
            feeds_file: autopost/feeds_crypto.txt
            script: autopost/pull_crypto.py
            max_per_cat: "5"
            schedule: "5 */3 * * *"
          - category: "Culture & Arts"
            slug: culture-arts
            feeds_file: autopost/feeds_cultute_arts.txt
            script: autopost/pull_cultute_arts.py
            max_per_cat: "10"
            schedule: "10 */3 * * *"
          - category: Entertainment
            slug: entertainment
            feeds_file: autopost/feeds_entertainment.txt
            script: autopost/pull_entertainment.py
            max_per_cat: "10"
            schedule: "15 */3 * * *"
          - category: "Food & Drink"
            slug: food-drink
            feeds_file: autopost/feeds_food_drink.txt
            script: autopost/pull_food_drink.py
            max_per_cat: "10"
            schedule: "20 */3 * * *"
          - category: Lifestyle
            slug: lifestyle
            feeds_file: autopost/feeds_lifestyle.txt
            script: autopost/pull_lifestyle.py
            max_per_cat: "10"
            schedule: "25 */3 * * *"
          - category: "Tech & AI"
            slug: tech-ai
            feeds_file: autopost/feeds_tech_ai.txt
            script: autopost/pull_tech_ai.py
            max_per_cat: "10"
            schedule: "30 */3 * * *"
          - category: Travel
            slug: travel
            feeds_file: autopost/feeds_travel.txt
            script: autopost/pull_travel.py
            max_per_cat: "10"
            schedule: "35 */3 * * *"
    env:
      SUMMARY_WORDS: "750"
      HTTP_TIMEOUT: "18"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"
      FEEDS_FILE: ${{ matrix.feeds_file }}
      CATEGORY: ${{ matrix.category }}
      MAX_PER_CAT: ${{ matrix.max_per_cat }}

    steps:
      - name: Determine schedule execution
        id: schedule_guard
        run: |
          if [[ "${{ github.event_name }}" != "schedule" || "${{ matrix.schedule }}" == "${{ github.event.schedule }}" ]]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/checkout@v4
        if: steps.schedule_guard.outputs.should_run == 'true'
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        if: steps.schedule_guard.outputs.should_run == 'true'
        with:
          python-version: "3.11"

      - name: Install deps
        if: steps.schedule_guard.outputs.should_run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install trafilatura readability-lxml lxml certifi

      - name: Ensure files
        if: steps.schedule_guard.outputs.should_run == 'true'
        run: |
          mkdir -p autopost data
          [ -s autopost/seen_all.json ] || echo "{}" > autopost/seen_all.json
          [ -s data/posts.json ] || echo "[]" > data/posts.json

      - name: Run ${{ matrix.category }} autoposter
        if: steps.schedule_guard.outputs.should_run == 'true'
        run: python3 ${{ matrix.script }}

      - name: Stage autopost changes
        id: git_status
        shell: bash
        if: steps.schedule_guard.outputs.should_run == 'true'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: No changes detected
        if: steps.schedule_guard.outputs.should_run == 'true' && steps.git_status.outputs.changed != 'true'
        run: echo "No autopost updates for ${{ matrix.category }}."

      - name: Open autopost PR
        if: steps.schedule_guard.outputs.should_run == 'true' && steps.git_status.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: autopost/${{ matrix.slug }}
          base: main
          commit-message: "autopost(${{ matrix.slug }}): refresh content"
          title: "Autopost: ${{ matrix.category }} updates"
          body: |
            Automated content refresh for **${{ matrix.category }}**.

            This PR was opened by the scheduled autopost workflow and will be updated on subsequent runs until merged.
          delete-branch: true
          draft: true
          
