name: Pull News (RSS → posts.json)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # çdo orë

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run pull_news.py
        run: python autopost/pull_news.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/posts.json autopost/seen_news.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update News/Politics posts [skip ci]"
            git push
          else
            echo "No changes."
          fi
